services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    restart: unless-stopped
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: nftracker
      MYSQL_USER: admin
      MYSQL_PASSWORD: myStrongPassword!
      MYSQL_ROOT_PASSWORD: myStrongPassword!
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      retries: 10
    networks:
      - internalnet

  redis:
    image: redis:bullseye
    container_name: rediscontainer
    restart: unless-stopped
    ports:
      - 6379:6379
    expose:
      - 6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - internalnet

  api:
    container_name: apicontainer
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nodeapi:1.0
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3001:3001
    expose:
      - 3001
    environment:
      DB_HOST: mysqldb
      DB_NAME: nftracker
      DB_USER: root
      DB_PORT: 3306
      DB_PASSWORD: myStrongPassword!
      JWT_SECRET: SDfhfdh645^$7
      EXPIRATION: 15h
      REDIS_PORT: 6379
      REDIS_URL: redis
    depends_on:
      mysqldb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
