version: '3'
services:
  api:
    container_name: apicontainer
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeapi:1.0
    ports:
      - 3001:3001
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: nftracker
      DB_USER: admin
      DB_PORT: 3306
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      EXPIRATION: 15h
      REDIS_PORT: 6379
      REDIS_URL: ${REDIS_URL}
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
